import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedAchievements() {
  console.log('🏆 Seeding achievements...');

  const achievements = [
    // ============================================
    // KILLS ACHIEVEMENTS
    // ============================================
    {
      name: 'First Blood',
      description: 'Få ditt första kill',
      category: 'kills',
      icon: '🎯',
      requirement: { type: 'kills', value: 1 },
      xpReward: 50,
      isHidden: false,
    },
    {
      name: 'Double Digits',
      description: 'Få 10 kills',
      category: 'kills',
      icon: '🔟',
      requirement: { type: 'kills', value: 10 },
      xpReward: 100,
      isHidden: false,
    },
    {
      name: 'Century Club',
      description: 'Få 100 kills',
      category: 'kills',
      icon: '💯',
      requirement: { type: 'kills', value: 100 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'Killing Spree',
      description: 'Få 500 kills',
      category: 'kills',
      icon: '⚔️',
      requirement: { type: 'kills', value: 500 },
      xpReward: 1000,
      isHidden: false,
    },
    {
      name: 'Grim Reaper',
      description: 'Få 1000 kills',
      category: 'kills',
      icon: '💀',
      requirement: { type: 'kills', value: 1000 },
      xpReward: 2000,
      isHidden: false,
    },
    {
      name: 'Headshot Master',
      description: 'Få 100 headshots',
      category: 'kills',
      icon: '🎯',
      requirement: { type: 'headshots', value: 100 },
      xpReward: 750,
      isHidden: false,
    },
    {
      name: 'Assist King',
      description: 'Få 100 assists',
      category: 'kills',
      icon: '🤝',
      requirement: { type: 'assists', value: 100 },
      xpReward: 500,
      isHidden: false,
    },

    // ============================================
    // OBJECTIVES ACHIEVEMENTS
    // ============================================
    {
      name: 'Point Capturer',
      description: 'Capture 10 punkter',
      category: 'objectives',
      icon: '🏁',
      requirement: { type: 'pointsCaptured', value: 10 },
      xpReward: 200,
      isHidden: false,
    },
    {
      name: 'Territory Master',
      description: 'Capture 50 punkter',
      category: 'objectives',
      icon: '🚩',
      requirement: { type: 'pointsCaptured', value: 50 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'Conqueror',
      description: 'Capture 100 punkter',
      category: 'objectives',
      icon: '👑',
      requirement: { type: 'pointsCaptured', value: 100 },
      xpReward: 1000,
      isHidden: false,
    },
    {
      name: 'Defender',
      description: 'Försvara 10 punkter',
      category: 'objectives',
      icon: '🛡️',
      requirement: { type: 'pointsDefended', value: 10 },
      xpReward: 200,
      isHidden: false,
    },
    {
      name: 'Guardian',
      description: 'Försvara 50 punkter',
      category: 'objectives',
      icon: '🔰',
      requirement: { type: 'pointsDefended', value: 50 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'Fortress',
      description: 'Försvara 100 punkter',
      category: 'objectives',
      icon: '🏰',
      requirement: { type: 'pointsDefended', value: 100 },
      xpReward: 1000,
      isHidden: false,
    },

    // ============================================
    // TEAMWORK ACHIEVEMENTS
    // ============================================
    {
      name: 'Medic',
      description: 'Återuppliva 10 lagkamrater',
      category: 'teamwork',
      icon: '💊',
      requirement: { type: 'revives', value: 10 },
      xpReward: 200,
      isHidden: false,
    },
    {
      name: 'Combat Medic',
      description: 'Återuppliva 50 lagkamrater',
      category: 'teamwork',
      icon: '⚕️',
      requirement: { type: 'revives', value: 50 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'Lifesaver',
      description: 'Återuppliva 100 lagkamrater',
      category: 'teamwork',
      icon: '👼',
      requirement: { type: 'revives', value: 100 },
      xpReward: 1000,
      isHidden: false,
    },
    {
      name: 'Supply Runner',
      description: 'Leverera 50 supplies',
      category: 'teamwork',
      icon: '📦',
      requirement: { type: 'suppliesDelivered', value: 50 },
      xpReward: 300,
      isHidden: false,
    },
    {
      name: 'Logistics Master',
      description: 'Leverera 200 supplies',
      category: 'teamwork',
      icon: '🚛',
      requirement: { type: 'suppliesDelivered', value: 200 },
      xpReward: 750,
      isHidden: false,
    },
    {
      name: 'Supply Chain',
      description: 'Leverera 500 supplies',
      category: 'teamwork',
      icon: '🏭',
      requirement: { type: 'suppliesDelivered', value: 500 },
      xpReward: 1500,
      isHidden: false,
    },

    // ============================================
    // SPECIAL ACHIEVEMENTS
    // ============================================
    {
      name: 'Welcome to the War',
      description: 'Spela din första match',
      category: 'special',
      icon: '🎮',
      requirement: { type: 'gamesPlayed', value: 1 },
      xpReward: 100,
      isHidden: false,
    },
    {
      name: 'Getting Started',
      description: 'Spela 10 matcher',
      category: 'special',
      icon: '🎯',
      requirement: { type: 'gamesPlayed', value: 10 },
      xpReward: 200,
      isHidden: false,
    },
    {
      name: 'Dedicated Player',
      description: 'Spela 50 matcher',
      category: 'special',
      icon: '🔥',
      requirement: { type: 'gamesPlayed', value: 50 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'Hardcore Veteran',
      description: 'Spela 100 matcher',
      category: 'special',
      icon: '💎',
      requirement: { type: 'gamesPlayed', value: 100 },
      xpReward: 1000,
      isHidden: false,
    },
    {
      name: 'First Victory',
      description: 'Vinn din första match',
      category: 'special',
      icon: '🏆',
      requirement: { type: 'gamesWon', value: 1 },
      xpReward: 150,
      isHidden: false,
    },
    {
      name: 'Winning Streak',
      description: 'Vinn 10 matcher',
      category: 'special',
      icon: '🥇',
      requirement: { type: 'gamesWon', value: 10 },
      xpReward: 300,
      isHidden: false,
    },
    {
      name: 'Champion',
      description: 'Vinn 50 matcher',
      category: 'special',
      icon: '👑',
      requirement: { type: 'gamesWon', value: 50 },
      xpReward: 750,
      isHidden: false,
    },
    {
      name: 'Legend',
      description: 'Vinn 100 matcher',
      category: 'special',
      icon: '⭐',
      requirement: { type: 'gamesWon', value: 100 },
      xpReward: 1500,
      isHidden: false,
    },
    {
      name: 'Level 5',
      description: 'Nå level 5',
      category: 'special',
      icon: '5️⃣',
      requirement: { type: 'level', value: 5 },
      xpReward: 250,
      isHidden: false,
    },
    {
      name: 'Level 10',
      description: 'Nå level 10',
      category: 'special',
      icon: '🔟',
      requirement: { type: 'level', value: 10 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'Level 25',
      description: 'Nå level 25',
      category: 'special',
      icon: '🌟',
      requirement: { type: 'level', value: 25 },
      xpReward: 1000,
      isHidden: false,
    },
    {
      name: 'Level 50',
      description: 'Nå level 50',
      category: 'special',
      icon: '💫',
      requirement: { type: 'level', value: 50 },
      xpReward: 2500,
      isHidden: false,
    },
    {
      name: 'K/D Warrior',
      description: 'Uppnå 2.0 K/D ratio',
      category: 'special',
      icon: '📊',
      requirement: { type: 'kdr', value: 2 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'K/D Champion',
      description: 'Uppnå 3.0 K/D ratio',
      category: 'special',
      icon: '📈',
      requirement: { type: 'kdr', value: 3 },
      xpReward: 1000,
      isHidden: false,
    },
    {
      name: 'Unstoppable',
      description: 'Uppnå 5.0 K/D ratio',
      category: 'special',
      icon: '🚀',
      requirement: { type: 'kdr', value: 5 },
      xpReward: 2000,
      isHidden: false,
    },
    {
      name: 'Winner',
      description: 'Uppnå 60% win rate',
      category: 'special',
      icon: '🎖️',
      requirement: { type: 'winRate', value: 60 },
      xpReward: 500,
      isHidden: false,
    },
    {
      name: 'Dominator',
      description: 'Uppnå 75% win rate',
      category: 'special',
      icon: '👑',
      requirement: { type: 'winRate', value: 75 },
      xpReward: 1000,
      isHidden: false,
    },
    {
      name: 'Undefeated',
      description: 'Uppnå 90% win rate',
      category: 'special',
      icon: '💎',
      requirement: { type: 'winRate', value: 90 },
      xpReward: 2500,
      isHidden: true, // Hidden achievement
    },
  ];

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { name: achievement.name },
      update: achievement,
      create: achievement,
    });
  }

  console.log(`✅ Seeded ${achievements.length} achievements`);
}
